name: Django CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    services:
      db:
        image: postgres:14-3.3
        env:
          POSTGRES_USER: optimeta
          POSTGRES_PASSWORD: optimeta
          POSTGRES_DB: optimetaPortal
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Pre-pull images
      run: |
        docker pull postgis/postgis:14-3.3
        docker pull ubuntu/20.04

    - name: Install docker-compose and msgfmt
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install docker-compose
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Tests
      run: |
        python manage.py test tests
    - name: Run UI Tests
      run: |
        docker-compose up -d
        python manage.py test tests-ui
